connect_bd_intf_net [get_bd_intf_pins axi_apb_bridge_0/APB_M] [get_bd_intf_pins SVNetEngine_0/s_apb]
connect_bd_intf_net [get_bd_intf_pins axi_bram_ctrl_0/BRAM_PORTA] [get_bd_intf_pins SVNetEngine_0/bram_0_a]
connect_bd_intf_net [get_bd_intf_pins axi_bram_ctrl_1/BRAM_PORTA] [get_bd_intf_pins SVNetEngine_0/bram_1_a]
connect_bd_intf_net [get_bd_intf_pins axi_bram_ctrl_2/BRAM_PORTA] [get_bd_intf_pins SVNetEngine_0/bram_2_a]
connect_bd_intf_net [get_bd_intf_pins axi_bram_ctrl_3/BRAM_PORTA] [get_bd_intf_pins SVNetEngine_0/bram_3_a]
connect_bd_net [get_bd_pins SVNetEngine_0/clk] [get_bd_pins zynq_ultra_ps_e_0/pl_clk0]
connect_bd_net [get_bd_pins SVNetEngine_0/rstn] [get_bd_pins proc_sys_reset_200/peripheral_aresetn]
connect_bd_net [get_bd_pins SVNetEngine_0/rstn_if] [get_bd_pins proc_sys_reset_333/peripheral_aresetn]
connect_bd_net [get_bd_pins SVNetEngine_0/intr_0] [get_bd_pins xlconcat_0/In3]
connect_bd_net [get_bd_pins SVNetEngine_0/intr_1] [get_bd_pins xlconcat_0/In4]
connect_bd_net [get_bd_pins SVNetEngine_0/intr_2] [get_bd_pins xlconcat_0/In5]
assign_bd_address [get_bd_addr_segs {zynq_ultra_ps_e_0/SAXIGP2/HP0_DDR_LOW zynq_ultra_ps_e_0/SAXIGP2/HP0_QSPI zynq_ultra_ps_e_0/SAXIGP2/HP0_PCIE_LOW zynq_ultra_ps_e_0/SAXIGP2/HP0_LPS_OCM }]
assign_bd_address [get_bd_addr_segs {SVNetEngine_0/s_apb_reg_map/s_apb_reg axi_cdma_0/S_AXI_LITE/Reg axi_cdma_1/S_AXI_LITE/Reg axi_cdma_2/S_AXI_LITE/Reg }]
assign_bd_address [get_bd_addr_segs {axi_bram_ctrl_0/S_AXI/Mem0 axi_bram_ctrl_1/S_AXI/Mem0 axi_bram_ctrl_2/S_AXI/Mem0 axi_bram_ctrl_3/S_AXI/Mem0 }]
set_property range 32K [get_bd_addr_segs {axi_cdma_0/Data/SEG_axi_bram_ctrl_0_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_0/Data/SEG_axi_bram_ctrl_1_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_0/Data/SEG_axi_bram_ctrl_2_Mem0}]
set_property range 128K [get_bd_addr_segs {axi_cdma_0/Data/SEG_axi_bram_ctrl_3_Mem0}]
set_property range 32K [get_bd_addr_segs {axi_cdma_1/Data/SEG_axi_bram_ctrl_0_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_1/Data/SEG_axi_bram_ctrl_1_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_1/Data/SEG_axi_bram_ctrl_2_Mem0}]
set_property range 128K [get_bd_addr_segs {axi_cdma_1/Data/SEG_axi_bram_ctrl_3_Mem0}]
set_property range 32K [get_bd_addr_segs {axi_cdma_2/Data/SEG_axi_bram_ctrl_0_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_2/Data/SEG_axi_bram_ctrl_1_Mem0}]
set_property range 64K [get_bd_addr_segs {axi_cdma_2/Data/SEG_axi_bram_ctrl_2_Mem0}]
set_property range 128K [get_bd_addr_segs {axi_cdma_2/Data/SEG_axi_bram_ctrl_3_Mem0}]
save_bd_design
